# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tinakurisu/Desktop/SDL2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tinakurisu/Desktop/SDL2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tinakurisu/Desktop/SDL2/CMakeFiles /Users/tinakurisu/Desktop/SDL2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tinakurisu/Desktop/SDL2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cpp_sdl2

# Build rule for target.
cpp_sdl2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpp_sdl2
.PHONY : cpp_sdl2

# fast build rule for target.
cpp_sdl2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_sdl2.dir/build.make CMakeFiles/cpp_sdl2.dir/build
.PHONY : cpp_sdl2/fast

TextureHandle/TextureHandle.o: TextureHandle/TextureHandle.cpp.o
.PHONY : TextureHandle/TextureHandle.o

# target to build an object file
TextureHandle/TextureHandle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_sdl2.dir/build.make CMakeFiles/cpp_sdl2.dir/TextureHandle/TextureHandle.cpp.o
.PHONY : TextureHandle/TextureHandle.cpp.o

TextureHandle/TextureHandle.i: TextureHandle/TextureHandle.cpp.i
.PHONY : TextureHandle/TextureHandle.i

# target to preprocess a source file
TextureHandle/TextureHandle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_sdl2.dir/build.make CMakeFiles/cpp_sdl2.dir/TextureHandle/TextureHandle.cpp.i
.PHONY : TextureHandle/TextureHandle.cpp.i

TextureHandle/TextureHandle.s: TextureHandle/TextureHandle.cpp.s
.PHONY : TextureHandle/TextureHandle.s

# target to generate assembly for a file
TextureHandle/TextureHandle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_sdl2.dir/build.make CMakeFiles/cpp_sdl2.dir/TextureHandle/TextureHandle.cpp.s
.PHONY : TextureHandle/TextureHandle.cpp.s

script.o: script.cpp.o
.PHONY : script.o

# target to build an object file
script.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_sdl2.dir/build.make CMakeFiles/cpp_sdl2.dir/script.cpp.o
.PHONY : script.cpp.o

script.i: script.cpp.i
.PHONY : script.i

# target to preprocess a source file
script.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_sdl2.dir/build.make CMakeFiles/cpp_sdl2.dir/script.cpp.i
.PHONY : script.cpp.i

script.s: script.cpp.s
.PHONY : script.s

# target to generate assembly for a file
script.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_sdl2.dir/build.make CMakeFiles/cpp_sdl2.dir/script.cpp.s
.PHONY : script.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cpp_sdl2"
	@echo "... TextureHandle/TextureHandle.o"
	@echo "... TextureHandle/TextureHandle.i"
	@echo "... TextureHandle/TextureHandle.s"
	@echo "... script.o"
	@echo "... script.i"
	@echo "... script.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

